name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: "2.30.0"
          inlineScript: |
            # Log in to Azure using the provided credentials
            echo "${{ secrets.azure_credentials }}" > myAzureCreds.json
            az login --service-principal --username $(jq -r '.clientId' myAzureCreds.json) --password $(jq -r '.clientSecret' myAzureCreds.json) --tenant $(jq -r '.tenantId' myAzureCreds.json)

            # Set the Azure subscription
            az account set --subscription ${{ secrets.azure_subscription }}

            # Deploy resources using Bicep template
            az deployment group create \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --template-file ./infra/main.bicep \
              --parameters @./infra/parameters.json

      - name: Deploy Azure Function
        run: |
          # Extract the Function App name from parameters.json
          FUNCTION_APP_NAME=$(jq -r '.functionAppName.value' infra/parameters.json)

          # Deploy the function app
          func azure functionapp publish $FUNCTION_APP_NAME --python

      - name: Run Tests
        run: |
          pytest tests/
