name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: "2.30.0" # Specify a version if needed
          inlineScript: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            az deployment sub create \
              --location eastus \
              --template-file ./infra/main.bicep \
              --parameters @./infra/parameters.json

      - name: Deploy Azure Function
        run: |
          func azure functionapp publish ${{ secrets.FUNCTION_APP_NAME }} --python

    # - name: Run Tests
    #   run: |
    #     pytest tests/
