name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: "2.30.0"
          inlineScript: |
            # Log in to Azure using the provided credentials directly from the secret
            CLIENT_ID=$(echo ${{ secrets.azure_credentials }} | jq -r '.clientId')
            CLIENT_SECRET=$(echo ${{ secrets.azure_credentials }} | jq -r '.clientSecret')
            TENANT_ID=$(echo ${{ secrets.azure_credentials }} | jq -r '.tenantId')
            echo "CLIENT_ID=$CLIENT_ID"
            echo "CLIENT_SECRET=****"
            echo "TENANT_ID=$TENANT_ID"

            az login --service-principal --username $CLIENT_ID --password $CLIENT_SECRET --tenant $TENANT_ID

            # Set the Azure subscription
            az account set --subscription ${{ secrets.azure_subscription }}

            # Debugging: Output the parameters.json file content
            echo "DEBUG: parameters.json contents:"
            cat infra/parameters.json

            # Extract the Function App name from parameters.json
            FUNCTION_APP_NAME=$(jq -r '.functionAppName.value' infra/parameters.json)

            # Debugging: Output the function app name
            echo "DEBUG: FUNCTION_APP_NAME=$FUNCTION_APP_NAME"

      - name: Install Azure Functions Core Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-3

      - name: Deploy Azure Function
        run: |
          # Use the extracted function app name
          func azure functionapp publish $FUNCTION_APP_NAME --python

      - name: Run Tests
        run: |
          pytest tests/
