name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Azure CLI
        uses: azure/CLI@v1

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure with Bicep
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file infra/main.bicep \
            --parameters functionAppName='my-function-app' resourceGroupName='${{ secrets.AZURE_RESOURCE_GROUP }}'

      - name: Deploy Azure Function
        run: |
          func azure functionapp publish my-function-app --python

      - name: Set up Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/
