name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: "2.30.0"
          inlineScript: |
            # Extract values from the azure_credentials secret using jq
            CLIENT_ID=$(echo '${{ secrets.azure_credentials }}' | jq -r '.clientId')
            CLIENT_SECRET=$(echo '${{ secrets.azure_credentials }}' | jq -r '.clientSecret')
            TENANT_ID=$(echo '${{ secrets.azure_credentials }}' | jq -r '.tenantId')

            # Log in to Azure using the extracted service principal credentials
            az login --service-principal --username $CLIENT_ID --password $CLIENT_SECRET --tenant $TENANT_ID

            # Set the Azure subscription
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            # Deploy resources using Bicep template
            az deployment group create \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --template-file ./infra/main.bicep \
              --parameters @./infra/parameters.json

      - name: Install Azure Functions Core Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-3

      - name: Deploy Azure Function
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.azure_subscription }}
          AZURE_CREDENTIALS: ${{ secrets.azure_credentials }}
        run: |
          # Extract the Function App name from parameters.json
          FUNCTION_APP_NAME=$(jq -r '.functionAppName.value' infra/parameters.json)
          # Debugging: Output the function app name
          echo "DEBUG: FUNCTION_APP_NAME=$FUNCTION_APP_NAME"
          # Log in to Azure again to ensure `func` has the right context
          az login --service-principal --username $(echo ${{ secrets.azure_credentials }} | jq -r '.clientId') --password $(echo ${{ secrets.azure_credentials }} | jq -r '.clientSecret') --tenant $(echo ${{ secrets.azure_credentials }} | jq -r '.tenantId')
          az account set --subscription ${{ secrets.azure_subscription }}
          # Deploy the function app
          func azure functionapp publish 'onnxcv' --python
